"use client"

import { useState } from "react"
import { 
  Plus, 
  Sparkles,
  Edit2,
  Trash2,
  Loader2,
  Download,
  Search,
  Eye,
  Check
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from "@/components/ui/dialog"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"
import { useToast } from "@/hooks/use-toast"
import { useUser, useFirestore, useCollection, useMemoFirebase, setDocumentNonBlocking, deleteDocumentNonBlocking } from "@/firebase"
import { collection, query, orderBy, doc } from "firebase/firestore"
import { exportToCSV } from "@/lib/csv-export"

const STANDARD_UNITS = [
  "Project", "Hour", "Day", "Month", "Package", "nos", 
  "kg", "g", "lbs", "oz", "modules", "sqft", 
  "feet", "meter", "cm", "inches"
]

export default function CatalogPage() {
  const { user } = useUser()
  const db = useFirestore()
  const { toast } = useToast()

  const [isAiLoading, setIsAiLoading] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [isViewOpen, setIsViewOpen] = useState(false)
  const [searchTerm, setSearchTerm] = useState("")
  const [editingItemId, setEditingItemId] = useState<string | null>(null)
  const [viewingItem, setViewingItem] = useState<any | null>(null)
  const [isCustomUnit, setIsCustomUnit] = useState(false)

  const [formData, setFormData] = useState({
    name: "",
    description: "",
    unitPrice: 0,
    unit: "Project",
    gstRate: 0.18
  })

  const catalogQuery = useMemoFirebase(() => {
    if (!db || !user) return null
    return query(collection(db, "users", user.uid, "productServices"), orderBy("name"))
  }, [db, user])

  const { data: items, isLoading } = useCollection(catalogQuery)

  const handleExportCSV = () => {
    if (!items) return
    const exportData = items.map(item => ({
      "Item Name": item.name,
      "Description": item.description || "",
      "Base Price": item.unitPrice,
      "GST Rate (%)": (item.gstRate || 0) * 100,
      "Unit Type": item.unit || "Project"
    }))
    exportToCSV(exportData, "Catalog_Export")
  }

  const handleAiDescribe = () => {
    if (!formData.name) {
      toast({ title: "Notice", description: "Please enter an item name first." })
      return
    }
    setIsAiLoading(true)
    setTimeout(() => {
      setFormData(prev => ({
        ...prev,
        description: `Professional ${prev.name} solution tailored for high-impact results, ensuring maximum efficiency and quality for your business requirements.`
      }))
      setIsAiLoading(false)
      toast({
        title: "Sparkle!",
        description: "Professional description generated by AI.",
      })
    }, 1000)
  }

  const resetForm = () => {
    setFormData({ name: "", description: "", unitPrice: 0, unit: "Project", gstRate: 0.18 })
    setEditingItemId(null)
    setIsCustomUnit(false)
  }

  const handleOpenDialog = (item?: any) => {
    if (item) {
      setEditingItemId(item.id)
      const isCustom = item.unit && !STANDARD_UNITS.includes(item.unit)
      setFormData({
        name: item.name,
        description: item.description || "",
        unitPrice: item.unitPrice,
        unit: item.unit || "Project",
        gstRate: item.gstRate || 0.18
      })
      setIsCustomUnit(isCustom)
    } else {
      resetForm()
    }
    setIsDialogOpen(true)
  }

  const handleViewDetails = (item: any) => {
    setViewingItem(item)
    setIsViewOpen(true)
  }

  const handleSave = () => {
    if (!user || !db || isSaving) return
    if (!formData.name || formData.unitPrice < 0) {
      toast({ title: "Error", description: "Valid Name and Price are required.", variant: "destructive" })
      return
    }

    setIsSaving(true)
    const catalogRef = collection(db, "users", user.uid, "productServices")
    const docId = editingItemId || doc(catalogRef).id
    const targetRef = doc(db, "users", user.uid, "productServices", docId)
    
    const itemData = {
      id: docId,
      name: formData.name,
      description: formData.description,
      unitPrice: formData.unitPrice,
      gstRate: formData.gstRate,
      unit: formData.unit,
      updatedAt: new Date().toISOString()
    }

    setDocumentNonBlocking(targetRef, itemData, { merge: true })
    
    setTimeout(() => {
      setIsSaving(false)
      toast({ 
        title: "Success", 
        description: editingItemId ? "Item updated in catalog." : "Item added to catalog." 
      })
      setIsDialogOpen(false)
      resetForm()
    }, 800)
  }

  const handleDelete = (itemId: string) => {
    if (!user || !db) return
    const itemRef = doc(db, "users", user.uid, "productServices", itemId)
    deleteDocumentNonBlocking(itemRef)
    toast({ title: "Deleted", description: "Item removed from catalog." })
  }

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
    }).format(value);
  }

  const filteredItems = items?.filter(item => 
    item.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    item.description?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    item.unit?.toLowerCase().includes(searchTerm.toLowerCase())
  ) || []

  const handleUnitChange = (val: string) => {
    if (val === "custom") {
      setIsCustomUnit(true)
      setFormData({ ...formData, unit: "" })
    } else {
      setIsCustomUnit(false)
      setFormData({ ...formData, unit: val })
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Service Catalog</h1>
          <p className="text-muted-foreground">Manage your standard products and services for quick quote generation.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleExportCSV}>
            <Download className="size-4 mr-2" /> Export CSV
          </Button>
          <Button className="bg-accent hover:bg-accent/90" onClick={() => handleOpenDialog()}>
            <Plus className="size-4 mr-2" /> Add Item
          </Button>
        </div>
      </div>

      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
        <Input 
          placeholder="Search items in catalog..." 
          className="pl-9 bg-card" 
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      <div className="rounded-lg border bg-card shadow-sm overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow className="bg-muted/30">
              <TableHead>Service / Product</TableHead>
              <TableHead>Description</TableHead>
              <TableHead>Unit</TableHead>
              <TableHead>Price</TableHead>
              <TableHead>GST</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              <TableRow>
                <TableCell colSpan={6} className="text-center py-8 text-muted-foreground">Loading catalog...</TableCell>
              </TableRow>
            ) : filteredItems.length === 0 ? (
              <TableRow>
                <TableCell colSpan={6} className="text-center py-8 text-muted-foreground">Catalog is empty or no results found.</TableCell>
              </TableRow>
            ) : (
              filteredItems.map((item) => (
                <TableRow key={item.id} className="group">
                  <TableCell className="font-semibold">{item.name}</TableCell>
                  <TableCell className="max-w-xs truncate text-xs text-muted-foreground" title={item.description}>
                    {item.description || "—"}
                  </TableCell>
                  <TableCell>
                    <span className="text-xs px-2 py-0.5 rounded-full bg-accent/10 text-accent font-medium">
                      {item.unit}
                    </span>
                  </TableCell>
                  <TableCell className="font-mono font-medium">
                    {formatCurrency(item.unitPrice)}
                  </TableCell>
                  <TableCell className="text-xs text-muted-foreground">
                    {item.gstRate * 100}%
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-1">
                      <Button variant="ghost" size="icon" className="size-8" onClick={() => handleViewDetails(item)}>
                        <Eye className="size-4" />
                      </Button>
                      <Button variant="ghost" size="icon" className="size-8" onClick={() => handleOpenDialog(item)}>
                        <Edit2 className="size-4" />
                      </Button>
                      
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <Button variant="ghost" size="icon" className="size-8 text-destructive">
                            <Trash2 className="size-4" />
                          </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                          <AlertDialogHeader>
                            <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                            <AlertDialogDescription>
                              This will permanently remove "{item.name}" from your catalog.
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter>
                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                            <AlertDialogAction onClick={() => handleDelete(item.id)} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
                              Delete
                            </AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    </div>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>

      {/* Add / Edit Dialog */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>{editingItemId ? 'Edit Catalog Item' : 'New Catalog Item'}</DialogTitle>
          </DialogHeader>
          <div className="grid gap-6 py-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="item-name">Item Name</Label>
                <Input 
                  id="item-name" 
                  placeholder="E.g. Web Development" 
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="item-unit">Unit Type</Label>
                <div className="space-y-2">
                  <Select 
                    value={isCustomUnit ? "custom" : formData.unit} 
                    onValueChange={handleUnitChange}
                  >
                    <SelectTrigger id="item-unit">
                      <SelectValue placeholder="Select unit" />
                    </SelectTrigger>
                    <SelectContent>
                      {STANDARD_UNITS.map(u => (
                        <SelectItem key={u} value={u}>{u}</SelectItem>
                      ))}
                      <SelectItem value="custom" className="text-accent font-bold">Custom...</SelectItem>
                    </SelectContent>
                  </Select>
                  {isCustomUnit && (
                    <Input 
                      placeholder="Enter custom unit (e.g. sq.m)" 
                      value={formData.unit}
                      onChange={(e) => setFormData({ ...formData, unit: e.target.value })}
                      className="h-8 text-xs"
                    />
                  )}
                </div>
              </div>
            </div>

            <div className="grid gap-2">
              <div className="flex items-center justify-between">
                <Label htmlFor="description">Description</Label>
                <Button 
                  variant="ghost" 
                  size="sm" 
                  className="h-8 text-[10px] text-accent font-semibold"
                  onClick={handleAiDescribe}
                  disabled={isAiLoading}
                >
                  <Sparkles className="size-3 mr-1" /> {isAiLoading ? "Generating..." : "AI Describe"}
                </Button>
              </div>
              <Textarea 
                id="description" 
                placeholder="Professional service description..." 
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                className="min-h-[100px]"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="price">Base Price (₹)</Label>
                <Input 
                  id="price" 
                  type="number" 
                  placeholder="0.00" 
                  value={formData.unitPrice || ""}
                  onChange={(e) => setFormData({ ...formData, unitPrice: parseFloat(e.target.value) || 0 })}
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="gst-rate">GST Rate</Label>
                <Select 
                  value={(formData.gstRate * 100).toString()} 
                  onValueChange={(val) => setFormData({ ...formData, gstRate: parseFloat(val) / 100 })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Tax %" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="0">0%</SelectItem>
                    <SelectItem value="5">5%</SelectItem>
                    <SelectItem value="12">12%</SelectItem>
                    <SelectItem value="18">18%</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDialogOpen(false)} disabled={isSaving}>Cancel</Button>
            <Button className="bg-accent" onClick={handleSave} disabled={isSaving}>
              {isSaving ? <Loader2 className="size-4 mr-2 animate-spin" /> : null}
              {editingItemId ? 'Update Item' : 'Save to Catalog'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* View Details Dialog */}
      <Dialog open={isViewOpen} onOpenChange={setIsViewOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Catalog Item Details</DialogTitle>
          </DialogHeader>
          {viewingItem && (
            <div className="space-y-4 py-4">
              <div className="space-y-1">
                <Label className="text-muted-foreground text-xs uppercase font-bold tracking-wider">Name</Label>
                <p className="text-lg font-bold">{viewingItem.name}</p>
              </div>
              <div className="space-y-1">
                <Label className="text-muted-foreground text-xs uppercase font-bold tracking-wider">Description</Label>
                <p className="text-sm leading-relaxed text-slate-600 bg-muted/30 p-3 rounded-md italic">
                  {viewingItem.description || "No description provided."}
                </p>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <Label className="text-muted-foreground text-xs uppercase font-bold tracking-wider">Base Price</Label>
                  <p className="font-mono font-bold text-accent">{formatCurrency(viewingItem.unitPrice)}</p>
                </div>
                <div className="space-y-1">
                  <Label className="text-muted-foreground text-xs uppercase font-bold tracking-wider">Unit Type</Label>
                  <p className="text-sm font-medium">{viewingItem.unit}</p>
                </div>
              </div>
              <div className="space-y-1">
                <Label className="text-muted-foreground text-xs uppercase font-bold tracking-wider">GST Rate</Label>
                <p className="text-sm">{viewingItem.gstRate * 100}%</p>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button className="w-full" onClick={() => setIsViewOpen(false)}>Close</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
